<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Update="thriftHub.db" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
		<Content Update="thrifthub.db" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />

		<!-- Entity Framework Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />

		<!-- MySQL -->
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />

		<!-- EF Core Tools -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- Email -->
		<PackageReference Include="MailKit" Version="4.17.0" />

		<!-- Sign in with Google / Apple -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.9" />
		<PackageReference Include="AspNet.Security.OAuth.Apple" Version="9.0.0" />
		<PackageReference Include="QRCoder" Version="1.8.0" />

	</ItemGroup>

</Project>